// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_couriers_repo.go -package=couriers_mocks
//

// Package couriers_mocks is a generated GoMock package.
package couriers_mocks

import (
	context "context"
	courier_domains "couriers/internal/Couriers/core/domains"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCouriersCache is a mock of CouriersCache interface.
type MockCouriersCache struct {
	ctrl     *gomock.Controller
	recorder *MockCouriersCacheMockRecorder
	isgomock struct{}
}

// MockCouriersCacheMockRecorder is the mock recorder for MockCouriersCache.
type MockCouriersCacheMockRecorder struct {
	mock *MockCouriersCache
}

// NewMockCouriersCache creates a new mock instance.
func NewMockCouriersCache(ctrl *gomock.Controller) *MockCouriersCache {
	mock := &MockCouriersCache{ctrl: ctrl}
	mock.recorder = &MockCouriersCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCouriersCache) EXPECT() *MockCouriersCacheMockRecorder {
	return m.recorder
}

// DeleteOrder mocks base method.
func (m *MockCouriersCache) DeleteOrder(ctx context.Context, personID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOrder", ctx, personID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOrder indicates an expected call of DeleteOrder.
func (mr *MockCouriersCacheMockRecorder) DeleteOrder(ctx, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOrder", reflect.TypeOf((*MockCouriersCache)(nil).DeleteOrder), ctx, personID)
}

// GetOrder mocks base method.
func (m *MockCouriersCache) GetOrder(ctx context.Context, personID int) (courier_domains.DispetchedOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, personID)
	ret0, _ := ret[0].(courier_domains.DispetchedOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockCouriersCacheMockRecorder) GetOrder(ctx, personID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockCouriersCache)(nil).GetOrder), ctx, personID)
}

// SaveToCache mocks base method.
func (m *MockCouriersCache) SaveToCache(ctx context.Context, order courier_domains.DispetchedOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveToCache", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveToCache indicates an expected call of SaveToCache.
func (mr *MockCouriersCacheMockRecorder) SaveToCache(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveToCache", reflect.TypeOf((*MockCouriersCache)(nil).SaveToCache), ctx, order)
}

// MockCouriersBroker is a mock of CouriersBroker interface.
type MockCouriersBroker struct {
	ctrl     *gomock.Controller
	recorder *MockCouriersBrokerMockRecorder
	isgomock struct{}
}

// MockCouriersBrokerMockRecorder is the mock recorder for MockCouriersBroker.
type MockCouriersBrokerMockRecorder struct {
	mock *MockCouriersBroker
}

// NewMockCouriersBroker creates a new mock instance.
func NewMockCouriersBroker(ctrl *gomock.Controller) *MockCouriersBroker {
	mock := &MockCouriersBroker{ctrl: ctrl}
	mock.recorder = &MockCouriersBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCouriersBroker) EXPECT() *MockCouriersBrokerMockRecorder {
	return m.recorder
}

// SendConfirm mocks base method.
func (m *MockCouriersBroker) SendConfirm(ctx context.Context, orderInfo courier_domains.DispetchedOrder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendConfirm", ctx, orderInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendConfirm indicates an expected call of SendConfirm.
func (mr *MockCouriersBrokerMockRecorder) SendConfirm(ctx, orderInfo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendConfirm", reflect.TypeOf((*MockCouriersBroker)(nil).SendConfirm), ctx, orderInfo)
}
