// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_auth_repo.go -package=auth_mocks
//

// Package auth_mocks is a generated GoMock package.
package auth_mocks

import (
	context "context"
	domains "couriers/internal/Auth/core/domains"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAuthDatabaseRepository is a mock of AuthDatabaseRepository interface.
type MockAuthDatabaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthDatabaseRepositoryMockRecorder
	isgomock struct{}
}

// MockAuthDatabaseRepositoryMockRecorder is the mock recorder for MockAuthDatabaseRepository.
type MockAuthDatabaseRepositoryMockRecorder struct {
	mock *MockAuthDatabaseRepository
}

// NewMockAuthDatabaseRepository creates a new mock instance.
func NewMockAuthDatabaseRepository(ctrl *gomock.Controller) *MockAuthDatabaseRepository {
	mock := &MockAuthDatabaseRepository{ctrl: ctrl}
	mock.recorder = &MockAuthDatabaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthDatabaseRepository) EXPECT() *MockAuthDatabaseRepositoryMockRecorder {
	return m.recorder
}

// GetCourier mocks base method.
func (m *MockAuthDatabaseRepository) GetCourier(ctx context.Context, login string) (domains.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCourier", ctx, login)
	ret0, _ := ret[0].(domains.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCourier indicates an expected call of GetCourier.
func (mr *MockAuthDatabaseRepositoryMockRecorder) GetCourier(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCourier", reflect.TypeOf((*MockAuthDatabaseRepository)(nil).GetCourier), ctx, login)
}

// GetUser mocks base method.
func (m *MockAuthDatabaseRepository) GetUser(ctx context.Context, login string) (domains.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, login)
	ret0, _ := ret[0].(domains.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockAuthDatabaseRepositoryMockRecorder) GetUser(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockAuthDatabaseRepository)(nil).GetUser), ctx, login)
}

// RegisterCourier mocks base method.
func (m *MockAuthDatabaseRepository) RegisterCourier(ctx context.Context, courier domains.Courier) (domains.Courier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterCourier", ctx, courier)
	ret0, _ := ret[0].(domains.Courier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterCourier indicates an expected call of RegisterCourier.
func (mr *MockAuthDatabaseRepositoryMockRecorder) RegisterCourier(ctx, courier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterCourier", reflect.TypeOf((*MockAuthDatabaseRepository)(nil).RegisterCourier), ctx, courier)
}

// RegisterUser mocks base method.
func (m *MockAuthDatabaseRepository) RegisterUser(ctx context.Context, user domains.User) (domains.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", ctx, user)
	ret0, _ := ret[0].(domains.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockAuthDatabaseRepositoryMockRecorder) RegisterUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockAuthDatabaseRepository)(nil).RegisterUser), ctx, user)
}
