// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_orders_repo.go -package=orders_mocks
//

// Package orders_mocks is a generated GoMock package.
package orders_mocks

import (
	context "context"
	orders_domains "couriers/internal/Orders/core/domains"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDatabasePostgres is a mock of DatabasePostgres interface.
type MockDatabasePostgres struct {
	ctrl     *gomock.Controller
	recorder *MockDatabasePostgresMockRecorder
	isgomock struct{}
}

// MockDatabasePostgresMockRecorder is the mock recorder for MockDatabasePostgres.
type MockDatabasePostgresMockRecorder struct {
	mock *MockDatabasePostgres
}

// NewMockDatabasePostgres creates a new mock instance.
func NewMockDatabasePostgres(ctrl *gomock.Controller) *MockDatabasePostgres {
	mock := &MockDatabasePostgres{ctrl: ctrl}
	mock.recorder = &MockDatabasePostgresMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabasePostgres) EXPECT() *MockDatabasePostgresMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockDatabasePostgres) CreateOrder(ctx context.Context, order orders_domains.Order) (orders_domains.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, order)
	ret0, _ := ret[0].(orders_domains.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockDatabasePostgresMockRecorder) CreateOrder(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockDatabasePostgres)(nil).CreateOrder), ctx, order)
}

// GetOrders mocks base method.
func (m *MockDatabasePostgres) GetOrders(ctx context.Context, personID int, limit, offset *int) ([]orders_domains.GetOrder, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, personID, limit, offset)
	ret0, _ := ret[0].([]orders_domains.GetOrder)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockDatabasePostgresMockRecorder) GetOrders(ctx, personID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockDatabasePostgres)(nil).GetOrders), ctx, personID, limit, offset)
}

// MockBrokerKafka is a mock of BrokerKafka interface.
type MockBrokerKafka struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerKafkaMockRecorder
	isgomock struct{}
}

// MockBrokerKafkaMockRecorder is the mock recorder for MockBrokerKafka.
type MockBrokerKafkaMockRecorder struct {
	mock *MockBrokerKafka
}

// NewMockBrokerKafka creates a new mock instance.
func NewMockBrokerKafka(ctrl *gomock.Controller) *MockBrokerKafka {
	mock := &MockBrokerKafka{ctrl: ctrl}
	mock.recorder = &MockBrokerKafkaMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrokerKafka) EXPECT() *MockBrokerKafkaMockRecorder {
	return m.recorder
}

// SendOrder mocks base method.
func (m *MockBrokerKafka) SendOrder(ctx context.Context, order orders_domains.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendOrder", ctx, order)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendOrder indicates an expected call of SendOrder.
func (mr *MockBrokerKafkaMockRecorder) SendOrder(ctx, order any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendOrder", reflect.TypeOf((*MockBrokerKafka)(nil).SendOrder), ctx, order)
}
