// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_dispetch_confirm_repo.go -package=dispetch_confirm_mocks
//

// Package dispetch_confirm_mocks is a generated GoMock package.
package dispetch_confirm_mocks

import (
	context "context"
	dispetch_domains "couriers/internal/Dispetch/core/domains"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDispetchPostgresDatabase is a mock of DispetchPostgresDatabase interface.
type MockDispetchPostgresDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDispetchPostgresDatabaseMockRecorder
	isgomock struct{}
}

// MockDispetchPostgresDatabaseMockRecorder is the mock recorder for MockDispetchPostgresDatabase.
type MockDispetchPostgresDatabaseMockRecorder struct {
	mock *MockDispetchPostgresDatabase
}

// NewMockDispetchPostgresDatabase creates a new mock instance.
func NewMockDispetchPostgresDatabase(ctrl *gomock.Controller) *MockDispetchPostgresDatabase {
	mock := &MockDispetchPostgresDatabase{ctrl: ctrl}
	mock.recorder = &MockDispetchPostgresDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDispetchPostgresDatabase) EXPECT() *MockDispetchPostgresDatabaseMockRecorder {
	return m.recorder
}

// ConfirmOrder mocks base method.
func (m *MockDispetchPostgresDatabase) ConfirmOrder(ctx context.Context, confirm dispetch_domains.Confirm) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmOrder", ctx, confirm)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmOrder indicates an expected call of ConfirmOrder.
func (mr *MockDispetchPostgresDatabaseMockRecorder) ConfirmOrder(ctx, confirm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmOrder", reflect.TypeOf((*MockDispetchPostgresDatabase)(nil).ConfirmOrder), ctx, confirm)
}
