// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mock_dispetch_orders_repo.go -package=dispetch_orders_mocks
//

// Package dispetch_orders_mocks is a generated GoMock package.
package dispetch_orders_mocks

import (
	context "context"
	dispetch_domains "couriers/internal/Dispetch/core/domains"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockOrdersDispetchDatabase is a mock of OrdersDispetchDatabase interface.
type MockOrdersDispetchDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersDispetchDatabaseMockRecorder
	isgomock struct{}
}

// MockOrdersDispetchDatabaseMockRecorder is the mock recorder for MockOrdersDispetchDatabase.
type MockOrdersDispetchDatabaseMockRecorder struct {
	mock *MockOrdersDispetchDatabase
}

// NewMockOrdersDispetchDatabase creates a new mock instance.
func NewMockOrdersDispetchDatabase(ctrl *gomock.Controller) *MockOrdersDispetchDatabase {
	mock := &MockOrdersDispetchDatabase{ctrl: ctrl}
	mock.recorder = &MockOrdersDispetchDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersDispetchDatabase) EXPECT() *MockOrdersDispetchDatabaseMockRecorder {
	return m.recorder
}

// DoBusy mocks base method.
func (m *MockOrdersDispetchDatabase) DoBusy(ctx context.Context, courierID, version int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoBusy", ctx, courierID, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// DoBusy indicates an expected call of DoBusy.
func (mr *MockOrdersDispetchDatabaseMockRecorder) DoBusy(ctx, courierID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoBusy", reflect.TypeOf((*MockOrdersDispetchDatabase)(nil).DoBusy), ctx, courierID, version)
}

// GetFreeCouriers mocks base method.
func (m *MockOrdersDispetchDatabase) GetFreeCouriers(ctx context.Context) ([]dispetch_domains.CourierInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFreeCouriers", ctx)
	ret0, _ := ret[0].([]dispetch_domains.CourierInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFreeCouriers indicates an expected call of GetFreeCouriers.
func (mr *MockOrdersDispetchDatabaseMockRecorder) GetFreeCouriers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFreeCouriers", reflect.TypeOf((*MockOrdersDispetchDatabase)(nil).GetFreeCouriers), ctx)
}

// SearchCourier mocks base method.
func (m *MockOrdersDispetchDatabase) SearchCourier(ctx context.Context, city string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCourier", ctx, city)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchCourier indicates an expected call of SearchCourier.
func (mr *MockOrdersDispetchDatabaseMockRecorder) SearchCourier(ctx, city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCourier", reflect.TypeOf((*MockOrdersDispetchDatabase)(nil).SearchCourier), ctx, city)
}

// MockOrdersDispetchBroker is a mock of OrdersDispetchBroker interface.
type MockOrdersDispetchBroker struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersDispetchBrokerMockRecorder
	isgomock struct{}
}

// MockOrdersDispetchBrokerMockRecorder is the mock recorder for MockOrdersDispetchBroker.
type MockOrdersDispetchBrokerMockRecorder struct {
	mock *MockOrdersDispetchBroker
}

// NewMockOrdersDispetchBroker creates a new mock instance.
func NewMockOrdersDispetchBroker(ctrl *gomock.Controller) *MockOrdersDispetchBroker {
	mock := &MockOrdersDispetchBroker{ctrl: ctrl}
	mock.recorder = &MockOrdersDispetchBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersDispetchBroker) EXPECT() *MockOrdersDispetchBrokerMockRecorder {
	return m.recorder
}

// SendDispetchedOrder mocks base method.
func (m *MockOrdersDispetchBroker) SendDispetchedOrder(ctx context.Context, orderID, version, courierID int, city string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendDispetchedOrder", ctx, orderID, version, courierID, city)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendDispetchedOrder indicates an expected call of SendDispetchedOrder.
func (mr *MockOrdersDispetchBrokerMockRecorder) SendDispetchedOrder(ctx, orderID, version, courierID, city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendDispetchedOrder", reflect.TypeOf((*MockOrdersDispetchBroker)(nil).SendDispetchedOrder), ctx, orderID, version, courierID, city)
}

// MockOrdersDispetchCache is a mock of OrdersDispetchCache interface.
type MockOrdersDispetchCache struct {
	ctrl     *gomock.Controller
	recorder *MockOrdersDispetchCacheMockRecorder
	isgomock struct{}
}

// MockOrdersDispetchCacheMockRecorder is the mock recorder for MockOrdersDispetchCache.
type MockOrdersDispetchCacheMockRecorder struct {
	mock *MockOrdersDispetchCache
}

// NewMockOrdersDispetchCache creates a new mock instance.
func NewMockOrdersDispetchCache(ctrl *gomock.Controller) *MockOrdersDispetchCache {
	mock := &MockOrdersDispetchCache{ctrl: ctrl}
	mock.recorder = &MockOrdersDispetchCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrdersDispetchCache) EXPECT() *MockOrdersDispetchCacheMockRecorder {
	return m.recorder
}

// CheckUnique mocks base method.
func (m *MockOrdersDispetchCache) CheckUnique(ctx context.Context, orderId int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckUnique", ctx, orderId)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckUnique indicates an expected call of CheckUnique.
func (mr *MockOrdersDispetchCacheMockRecorder) CheckUnique(ctx, orderId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckUnique", reflect.TypeOf((*MockOrdersDispetchCache)(nil).CheckUnique), ctx, orderId)
}

// SearchCourier mocks base method.
func (m *MockOrdersDispetchCache) SearchCourier(ctx context.Context, city string) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchCourier", ctx, city)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SearchCourier indicates an expected call of SearchCourier.
func (mr *MockOrdersDispetchCacheMockRecorder) SearchCourier(ctx, city any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchCourier", reflect.TypeOf((*MockOrdersDispetchCache)(nil).SearchCourier), ctx, city)
}

// UpdateCache mocks base method.
func (m *MockOrdersDispetchCache) UpdateCache(ctx context.Context, couriersByGroupCity map[string]map[int]dispetch_domains.FreeCourierInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCache", ctx, couriersByGroupCity)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCache indicates an expected call of UpdateCache.
func (mr *MockOrdersDispetchCacheMockRecorder) UpdateCache(ctx, couriersByGroupCity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCache", reflect.TypeOf((*MockOrdersDispetchCache)(nil).UpdateCache), ctx, couriersByGroupCity)
}
